// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolders(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolders'](arg1, arg2, arg3);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DuplicateTemplate(arg1) {
  return window['go']['main']['App']['DuplicateTemplate'](arg1);
}

export function ExportTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportTemplate'](arg1, arg2, arg3);
}

export function GenerateBat(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateBat'](arg1, arg2, arg3);
}

export function GenerateSh(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSh'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function ImportTemplate(arg1) {
  return window['go']['main']['App']['ImportTemplate'](arg1);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['main']['App']['OnSecondInstanceLaunch'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RenameTemplate(arg1, arg2) {
  return window['go']['main']['App']['RenameTemplate'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2);
}

export function ScanFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanFolder'](arg1, arg2, arg3);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function ValidateName(arg1) {
  return window['go']['main']['App']['ValidateName'](arg1);
}

export function ValidateTree(arg1) {
  return window['go']['main']['App']['ValidateTree'](arg1);
}
