// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {options} from '../models';

export function CreateFolders(arg1:string,arg2:string,arg3:Array<backend.Node>):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DuplicateTemplate(arg1:string):Promise<backend.Template>;

export function ExportTemplate(arg1:string,arg2:string,arg3:Array<backend.Node>):Promise<void>;

export function GenerateBat(arg1:string,arg2:string,arg3:Array<backend.Node>):Promise<string>;

export function GenerateSh(arg1:string,arg2:string,arg3:Array<backend.Node>):Promise<string>;

export function GetSettings():Promise<backend.Settings>;

export function GetTemplates():Promise<Array<backend.Template>>;

export function ImportTemplate(arg1:string):Promise<backend.Template>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function QuitApp():Promise<void>;

export function RenameTemplate(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;

export function SaveTemplate(arg1:string,arg2:Array<backend.Node>):Promise<void>;

export function ScanFolder(arg1:string,arg2:boolean,arg3:number):Promise<Array<backend.Node>>;

export function SetDirty(arg1:boolean):Promise<void>;

export function ValidateName(arg1:string):Promise<boolean|string>;

export function ValidateTree(arg1:Array<backend.Node>):Promise<void>;
